UniBee-Billing/unibee-admin-portal

- specs/utils/error.spec.ts
- specs/utils/is.spec.ts
- src/App.tsx
- src/components/about/ContactCard.tsx
- src/components/about/aboutUniBee.tsx
- src/components/about/license.tsx
- src/hooks/useFetch.ts
- src/hooks/useVersion.ts
- src/requests/client.ts
- src/utils/clipboard.ts
- src/utils/index.ts
- src/utils/loading.ts
- src/utils/version.ts
> feat: add about page

- src/components/about/aboutUniBee.tsx
Display profile email on about page
None.
> feat: display profile email on about page

- package.json
- src/components/countrySelector.tsx
- src/components/panelSwitch.tsx
- src/components/subscription/plan.tsx
- src/components/user/assignSub/accountTypeForm.tsx
- src/components/user/assignSub/accountTypeSwitch.tsx
- src/components/user/assignSub/assignSubModal.tsx
- src/components/user/assignSub/businessAccountForm.tsx
- src/components/user/assignSub/checkoutItem.tsx
- src/components/user/assignSub/personalAccountForm.tsx
- src/components/user/assignSubModal.tsx
- src/components/user/subscriptionTab.tsx
- src/hooks/index.ts
- src/hooks/useCountries.ts
- src/requests/index.ts
- src/shared.types.ts
- src/stores/index.ts
- src/utils/debounce.ts
- src/utils/index.ts
- yarn.lock
Support users can fill their information while using assign subscription feature
None.
> perf: assign subscription

- src/components/user/assignSub/assignSubModal.tsx
Display tax even tax is eq to 0
None.
> perf: display tax even tax is eq to 0

- src/components/user/assignSub/assignSubModal.tsx
Show discount percentage if discount code is percentage code
None.
> perf: show discount percentage if discount code is percentage code

- .github/workflows/release-whatever.yml
Add release arbitrary version CI script
None.
> feat: add release arbitrary version ci script

- src/components/ui/paymentSelector.tsx
Make the whole element as select area
None.
> perf: make the whole element as select area

- src/components/discountCode/detail.tsx
Support 100 percent discount code
None.
> feat: support 100 percent discount code

- src/components/user/assignSub/accountTypeForm.tsx
- src/components/user/assignSub/assignSubModal.tsx
Fix submit assign action failed when close require payment switch
None.
> fix: submit assign action failed when close require payment switch

- src/components/analytics/index.tsx
- src/components/user/assignSub/accountTypeForm.tsx
Set default account type to individual to avoid lose select state when user first use UniBee
None.
> fix: set default account type to individual

- src/components/user/assignSub/accountTypeForm.tsx
- src/shared.types.ts
Add none to account type enum
None.
> fix: add none to account type enum

- src/components/sidebar/about/aboutUniBee.tsx
- src/components/sidebar/sidebar.tsx
Update color of user info & about text to white
None.
> fix: text color

- src/components/discountCode/usageDetail.tsx
- src/components/subscription/invoicesTab.tsx
- Fixed user col width
- Display user email to avoid display empty string when user name is empty
None.
> fix: ui bugs

- .github/workflows/secrets-scanner.yml
Scan secrets using gitleaks when code push
None.
> feat(ci): scan secrets using gitleaks when code push

- src/components/login/otpLogin.tsx
- src/components/login/passwordLogin.tsx
- src/components/myAccount/profile.tsx
Remove APP_PATH from navigate path
None.
> fix: remove APP_PATH from navigate path

- src/components/settings/subscriptionConfig.tsx
Fix value of show invoice switch
None.
> fix: value of show invoice switch

- src/components/settings/appConfig/index.tsx
- src/components/settings/appConfig/paymentCallbackLinkEditModal.tsx
Add setting item for update payment callback link
None.
> feat: add setting item for update payment callback link

- src/components/discountCode/detail.tsx
- src/components/discountCode/helpers.ts
- src/components/discountCode/list.tsx
- src/components/discountCode/updateDiscountCodeQuantityModal.tsx
- src/utils/is.ts
Improve discount code page
None.
> perf: improve discount code page

- .github/workflows/release-whatever.yml
Sometimes we need release a temp version to external project such as MLX, but it's not part of our version plan, in this case , you can publish a `v*.*.*-arb.*` version, it will trigger release action and build docker image based on latest commit hash, but it will not generate changelogs, nor will it affect open-source version plan, it's just a temp version.
None.
> perf: add arb tag format

- src/components/discountCode/detail.tsx
- src/components/discountCode/helpers.ts
- src/components/discountCode/list.tsx
- src/components/discountCode/usageDetail.tsx
- src/shared.types.ts
- Update label of valid date range form item
- Add col to display the code whether is recurring
None.
> chore: update label of valid date range form item

- src/components/discountCode/detail.tsx
Update the width of label col to 180 pixel
None.
> fix: update the width of label col to 180 pixel

- src/components/user/assignSub/assignSubModal.tsx
Fix preview does not working if the user fill the form before select plans
None.
> fix: assign subscription modal bug

- package.json
- src/components/sidebar/sideMenu.tsx
- src/components/subscription/subscription.tsx
- yarn.lock
> chore: bump antd to 5.22.0

- src/components/subscription/subscription.tsx
Fix date picker not working when update open state in onBlur handler
None.
> fix: date picker not working when update open state in onBlur handler

- src/components/subscription/plan.tsx
- src/components/user/assignSub/assignSubModal.tsx
- src/components/user/assignSub/infoItem.tsx
- src/components/user/assignSub/planSelector.tsx
- src/components/user/assignSub/userInfoCard.tsx
- src/components/user/subscriptionTab.tsx
- src/hooks/useLoading.ts
- src/hooks/usePlans.ts
- src/shared.types.ts
- src/utils/formatter.ts
- src/utils/index.ts
Refactor assign subscription modal
None.
> refactor: assign subscription modal

- src/components/report/fieldsSelector/fieldsSearchInput.tsx
- src/components/report/fieldsSelector/index.tsx
- src/components/report/helpers.ts
- src/components/report/index.css
- src/components/report/index.tsx
- src/components/report/preview/fieldItem.tsx
- src/components/report/preview/index.tsx
- src/utils/formatter.ts
Fix report page fields reactive bugs
None.
> fix: report page fields reactive bugs

- src/components/report/index.tsx
> fix: report page bugs

- src/components/report/fieldsSelector/fieldsSearchInput.tsx
- src/components/report/fieldsSelector/index.tsx
- src/components/report/index.tsx
- src/utils/formatter.ts
> fix: report tab bugs

- src/components/report/addNewTemplateButton.tsx
- src/components/report/index.tsx
Reset state when create new template
None
> feat: reset state when create new template

- src/components/report/index.tsx
- src/hooks/useExportColumnList.ts
Add default value for columns
None.
> fix: add default value for columns

- src/components/signup.tsx
Fix incorrect navigate path
None.
> fix: incorrect navigate path

- .cspell.json
- src/components/user/detail.tsx
- src/components/user/userNote.tsx
- src/helpers/index.ts
- src/requests/index.ts
- src/shared.types.ts
Add user side note on user detail page.
> feat: add user note on user detail page

- src/App.tsx
- src/components/subscription/adminNote.tsx
- src/components/subscription/detail.css
- src/components/subscription/detail.tsx
- src/components/user/detail.tsx
- src/components/user/userNote.tsx
styling: make <note /> the same height as screen height
> style: make note height same as screen heigh

- src/components/user/paymentCards.tsx
- src/requests/index.ts
Add a button to remove payment card
> feat: add 'remove-card' op to list of payment card

- .cspell.json
- src/App.tsx
- src/components/subscription/adminNote.tsx
- src/components/subscription/detail.css
- src/components/subscription/detail.tsx
- src/components/subscription/modals/changePlan.tsx
- src/components/user/detail.tsx
- src/components/user/paymentCards.tsx
- src/components/user/userNote.tsx
- src/helpers/index.ts
- src/requests/index.ts
- src/shared.types.ts
> Release v1.3.1

- src/components/report/preview/index.tsx
Convert milliseconds to seconds before execute export
None.
> fix: convert milliseconds to seconds before execute export

- src/components/report/preview/index.tsx
> fix: convert milliseconds to seconds before execute export (#95)

- .cspell.json
- src/App.tsx
- src/components/subscription/adminNote.tsx
- src/components/subscription/detail.css
- src/components/subscription/detail.tsx
- src/components/subscription/invoicesTab.tsx
- src/components/subscription/modals/changePlan.tsx
- src/components/user/detail.tsx
- src/components/user/paymentCards.tsx
- src/components/user/userNote.tsx
- src/helpers/index.ts
- src/requests/index.ts
- src/shared.types.ts
Remove 'add-invoice' button on invoiceList page
> Feat 305/remove add iv icon

- src/components/discountCode/detail.tsx
- src/components/discountCode/list.tsx
Fix discount code module issues
None
> fix: discount code module issues

- src/components/discountCode/detail.tsx
- src/components/discountCode/header.tsx
- src/components/discountCode/list.tsx
- src/components/table/exportButton.tsx
- src/components/ui/statusTag.tsx
- src/constants.ts
- src/shared.types.ts
Enable delete discount code button for all status
None.
> feat: enable delete discount code button for all status

- src/components/discountCode/detail.tsx
chore: update Delete to Archive
None
> chore: update `Delete` to `Archive`

- src/components/discountCode/detail.tsx
> chore: update delete popup text

- src/hooks/useFetch.ts
- src/hooks/usePlans.ts
- src/requests/client.ts
Rethrow error when code is eq to 51
None.
> fix: rethrow error when code is eq to 51

- src/hooks/useCountries.ts
Early return if the countries data is undefined
None.
> fix: early return if data is undefined

- src/components/discountCode/header.tsx
- src/components/discountCode/list.tsx
Update text of coupon code ui elements
None
> perf: update text of coupon code ui elememts

- src/components/discountCode/detail.tsx
- src/components/discountCode/list.tsx
- Change Billing type to Type
- Update the delete discount code toast message
None.
> [Chore] update text

- src/components/subscription/modals/changePlan.tsx
> chore: cleanup

- src/components/shared/userInfo.tsx
- src/components/user/promoCreditTxHist.tsx
- src/requests/index.ts
- add sort on TxList creatTime
- add email filter on TxList email field
> feat: add sort/filter on creditTxList

- src/components/user/list.tsx
- src/components/user/promoCreditTxHist.tsx
- src/requests/index.ts
- src/shared.types.ts
- add CreditTxList export button
- add total credit added/consumed stat
> feat: add export creditTxList

- src/components/invoice/detail.tsx
- src/components/subscription/modals/invoiceDetail.tsx
- src/components/ui/couponPopover.tsx
- use copyToClipobard button on wherever invoice Id appeared
- remove wrong discount code popover placement besides a promoCredit info block
> style: minor improvement

- src/components/user/promoCreditTxHist.tsx
- src/helpers/index.ts
> style: add icon for credit usage stat,

- src/components/billableMetrics/detail.tsx
- src/components/settings/appConfig/sendGridKeyModal.tsx
- src/components/settings/appConfig/vatKeyModal.tsx
- src/components/settings/webHooks/webhookLogs.tsx
- replace old copy-to-clipboard hook with new ui component
> chore: use new copy-to-clipboard button

- src/components/invoice/detail.tsx
- src/components/subscription/detail.tsx
- src/components/subscription/list.tsx
- src/components/subscription/modals/changePlan.tsx
- src/components/subscription/modals/invoiceDetail.tsx
- src/components/subscription/paymentTab.tsx
- src/components/subscription/subscription.tsx
- src/components/ui/couponPopover.tsx
- src/components/user/assignSub/assignSubModal.tsx
- src/components/user/promoCreditTxHist.tsx
- src/components/user/subscriptionTab.tsx
- use <MinusOutline /> icon to replace null
- move money symbol before value in some pages
- add missing subtotal in Invoice Detail modal
- use copyToClipboard comp beside an invoiceId text
- add latest invoiceId in subscrition detail info block
- add recordId, note, creditAmt pre-post change to creditTxList
> chore: styling and small improvement

- src/components/user/promoCreditTxHist.tsx
> style: re-order creditTxList header

- src/components/user/promoCreditTxHist.tsx
- src/constants.ts
- src/shared.types.ts
- update creditTx type description
> chore: update creditTxType description

- src/components/subscription/subscription.tsx
- src/components/user/promoCreditTab.tsx
- src/components/user/promoCreditTxHist.tsx
- src/components/user/subscriptionTab.tsx
- src/constants.ts
- src/shared.types.ts
- rename creditTxType to more descriptive
- use dash to indicate Not-applied for creditAmt/DiscountAmt/Addons
> feat: rename creditTxType to more descriptive

- src/components/discountCode/detail.tsx
- src/shared.types.ts
- add advanced config items in discount code detail page
> feat: add advnaced discount code config items

- src/components/sidebar/sideMenu.tsx
- src/constants.ts
- src/routes.tsx
- add promo-credit page in permission setting
> fix: add promo-credit to permission setting

- src/components/user/promoCreditTxHist.tsx
- fix: sorting creditTxList caused page reset to 0
> fix: sorting cause page reset to 0

- src/components/discountCode/detail.tsx
- hide discount code advanced config(not ready for v1.5.0 release)
> feat: hide discount code advanced config(not ready for release)

- src/components/user/promoCreditTxHist.tsx
- src/shared.types.ts
- credit amount updated by whom is missing if consumed by user themselves
> fix: creditTx updated by whom is missing

- src/components/discountCode/detail.tsx
- src/components/subscription/invoicesTab.tsx
- src/components/subscription/modals/newInvoice.tsx
- src/hooks/useAppInitialize.ts
- src/shared.types.ts
- src/stores/index.ts
- remove misleading note for upgrade-only discount code
- read tax rate from user profile when manually creating a draft invoice
> feat: add default taxRate when manually creating invoice

- src/components/subscription/invoicesTab.tsx
- src/components/user/assignSub/assignSubModal.tsx
- fix: toggling "require payment" not trigger preview rerun
> fix: toggling 'require payment' not triggering order-preview

- src/components/discountCode/detail.tsx
- src/components/login/passwordLogin.tsx
- src/components/settings/index.tsx
- src/components/settings/paymentGateways.tsx
- src/hooks/useAppInitialize.ts
- src/requests/index.ts
- src/shared.types.ts
- add skeleton component to implement new payment gateway config UI
- add console.log output to show permission/role(why still empty or 404 page after login)
> feat: add new gateway config tab in Setting

- src/components/settings/appConfig/index.tsx
- remove displayName/icons hard-coding in <payment selector>
- some gateways don't need webhook config, hide the tab
> fix: wire-transfer modal need update in old AppConfig tab

- .cspell.json
- src/App.tsx
- src/components/analytics/index.tsx
- src/components/login/passwordLogin.tsx
- src/components/settings/appConfig/index.tsx
- src/components/settings/appConfig/wireTransferModal.tsx
- src/components/settings/integrations.tsx
- src/components/settings/paymentGateways.tsx
- src/requests/index.ts
- src/shared.types.ts
- try to implemtn re-ordering(not done yet)
- fix: wire-transfer amt scale-up/down
- read gatewayconfig from BE everytime config page is loaded, instead of reading from store
> feat: implement gatewayConfig re-ordering

- src/components/settings/appConfig/exchangeRateKeyModal.tsx
- src/components/settings/integrations.tsx
- src/components/settings/paymentGateways.tsx
- src/components/ui/paymentSelector.tsx
- src/requests/index.ts
- re-implement gateway config list sort
> feat: re-implement gatewayList sort

- src/components/myAccount/profile.tsx
- style: add icon on 'password managment' button
> style: add key-icon on password-mgr button

- src/components/settings/appConfig/wireTransferModal.tsx
- src/components/settings/index.tsx
- src/components/shared/userInfo.tsx
- src/components/subscription/invoicesTab.tsx
- src/components/subscription/subscription.tsx
- src/components/user/subscriptionTab.tsx
- src/helpers/index.ts
- src/shared.types.ts
- fix: amin-manually-created invoice(via wire-transfer) should have mark-as-paid button enabled
-
> fix: wire-transfer invoice should have 'mark as paid' button

- src/components/settings/paymentGateways.tsx
- fix: check webhook key validity before submit
> fix: check webhook key validity before submit

- src/components/ui/paymentSelector.tsx
- style: add 'ARV' tag to archived payment method
> style: add 'ARV' tag to archived payment method

- src/components/discountCode/detail.tsx
- src/shared.types.ts
- feat: add discount code plan-apply option: apply to all, to the selected, except the selected
> feat: add options to code apply-to-what-plans

- src/components/discountCode/detail.tsx
- feat: allow changing code apply option after code being activated
> feat: allow to edit code-apply-type after activating

- src/components/subscription/list.tsx
- feat: add search/select-all in planName filter on SubscriptionList page
> feat: add search/select-all in plan filter on subscriptionList page

- src/components/sidebar/sidebar.tsx
> fix: pass unneeded props

- src/components/myAccount/merchantInfo.tsx
- feat: add img-crop tool before uploading logo
> feat: add img-crop tool before upload logo

- src/components/myAccount/merchantInfo.tsx
feat: add more cropOption before uploading logo
> feat: add more cropOption

- src/App.tsx
- try to fix the blank page after refreshing page
> fix: try to fix why refreshing page would cause blank page

- src/App.tsx
- src/stores/index.ts
- try to fix page blank after manual refresh
> fix: page became blank after manual refresh

- src/App.tsx
> debug: add console.log to check initialize call

- src/App.tsx
> fix: run initialize after app mounted

- src/components/myAccount/merchantInfo.tsx
- feat: add svg for logo upload
> feat: add svg support for logo uploading

- src/components/discountCode/detail.tsx
- src/components/settings/paymentGateways.tsx
- feat: reword "svg support, file constraint" on icon upload 
- code detail: applied plans name need to be ellipsized after 3 lines
> style: rewordign on gateway icon helper

- src/components/subscription/invoicesTab.tsx
- src/components/subscription/modals/invoiceDetail.tsx
- src/components/subscription/modals/newInvoice.tsx
- src/components/ui/paymentSelector.tsx
- src/components/user/assignSub/assignSubModal.tsx
- feat: allow to create refund invoice from main invoiceList page
> feat: allow to create refund iv in main invoiceList

- .cspell.json
- src/components/subscription/list.tsx
- src/components/user/list.tsx
- src/constants.ts
- src/shared.types.ts
- fix: remove INITIATING sub-status in filter
> feat: remove INITIATING substatus in status filter

- src/components/discountCode/detail/generalConfig.tsx
- src/components/plan/detail.tsx
- src/constants.ts
- src/helpers/index.ts
- refactor: remove hard-coded currency constant, use the one defined in store(initialized from BE)
> refactor: remove hard-coded CURRENCY constant

- src/components/subscription/paymentTab.tsx
- src/requests/index.ts
- fix: transaction list req call: currency params was ignored
> fix: TxList req ignored currency param

- src/components/plan/planList.tsx
- src/constants.ts
- src/requests/index.ts
- src/shared.types.ts
- feat: add plan archive modal and its operations
> feat: add plan archive modal and its operation

- src/assets/user.svg
- src/components/sidebar/logoWithAction.tsx
- src/components/sidebar/sidebar.tsx
- feat: add popover text of account info on bottom-left icon
> feat: add user info popover on bottom-left icon

- src/components/subscription/list.tsx
- fix: on subscriptionLIst page, fetchPlan should include archived plans
> fix: fetchPlan should include archived plan

- src/components/appSearch.css
- src/components/appSearch.tsx
- src/components/discountCode/detail/generalConfig.tsx
- src/components/subscription/userAccountTab.tsx
- src/components/user/detail.tsx
- fix: app search result -> user list: click user didn't update the underling user profile page
> fix: appSearch result: click didn't update the use page

- .github/workflows/update-version.yml
- fix: error in "update package version" job after release
> ci: fix update version error in release workflow

- src/components/discountCode/list.tsx
1.Merge “Discount Type” “Amount“ “Percentage“ into 1 column named “ Discount Info”, if it’s fixed amount, then display the discount amount number and currency; if it’s percentage type, then display the percentage number (eg: 30%)
2.Merge “Type” and “Cycle Limit” into 1 column, placed after “Discount Info“, named “Recurring Cycle”
> fix:Simplify the Discount Code list view

- src/components/discountCode/list.tsx
fix: beta407 number size & svg center
> fix: beta407 number size & svg center

- src/components/plan/detail/basicConfig.tsx
> fix:beta419 Billing Period Input

- src/components/plan/planList.tsx
> fix:beta 421 yarn lint&fetchPlan

- src/components/subscription/userAccountTab.tsx
- chore: hide sendMetricEvent logic and UI element
> fix: hide sendMetricEvent logic and Element

- src/components/settings/gatewayConfig/pubPriKeySetup.tsx
- src/requests/index.ts
- fix: gateway config: "subgateway" need to be passed to onSave req
> fix: subGateway not passed to saveGateway req

- src/components/plan/detail/basicConfig.tsx
- src/components/plan/detail/constants.ts
- src/components/plan/planList.tsx
- src/shared.types.ts
> feat:beta446 add internal plan name

- src/components/myAccount/index.tsx
- src/components/myAccount/merchantInfo.tsx
- src/components/myAccount/profile.tsx
- src/requests/index.ts
> feat:beta423  save Admin---My Account---My profile

- src/components/user/assignSub/assignSubModal.tsx
> Feat:beta 449 Assign Sub improvement  for Develop/v1.7.2
